---
opsman-configuration:
  vsphere:
    vcenter:
      url: ((vsphere_vcenter.url))
      username: ((vsphere_vcenter.username))
      password: ((vsphere_vcenter_password))
      datastore: ((vsphere_vcenter.datastore))
      ca_cert: ((vsphere_vcenter.ca_cert)) # leave blank
      host: ((vsphere_vcenter.host))                     # vCenter host to deploy Ops Manager in
      datacenter: ((vsphere_vcenter.datacenter))
      resource_pool: ((vsphere_vcenter.resource_pool))
      folder: ((vsphere_vcenter.folder))
      insecure: ((vsphere_vcenter.insecure))                            # 1 insecure, 0 secure
    disk_type: ((vsphere_disk_type))                          # example: thin|thick
    private_ip: ((vsphere_private_ip))
    dns: ((vsphere_dns))
    ntp: ((vsphere_ntp))                     # example: ntp.ubuntu.com
    ssh_password: ((vsphere_vcenter_password))
    ssh_public_key: ((vsphere_ssh_public_key))           # for OpsManager >= 2.3
    hostname: ((vsphere_hostname))
    network: ((vsphere_network))                 # vcenter network to deploy to
    netmask: ((vsphere_netmask))
    gateway: ((vsphere_gateway))
    vm_name: ((vsphere_vm_name))